:PROPERTIES:
:ID:       d982ba25-96ae-4bf2-afd1-60641c711bcb
:END:
#+title: Mini Essay
#+date: [2025-08-16 Sat 10:56]

* The Dilemma
** Why? Choose something and never turn back. Has it always been like this ?
Trader or Industrialist?
How to get over this dilemma?
*Looking back*
I have never run an industrial company before ,infact i have once run away from a production workshop once because i felt spending 8 hours a day in the factory is making me to miss out the life outside of it.
But I have ppl say to me that I am good at Speaking, have the charismatic presence and have worked in business development and in some places in the sales area.
I have always believed that trading goods involved travelling to differnet parts of the world nad helping them with providing them what they want. Meetnig new ppl, forging new alliances, taking part in different cultures have always fancied me, than this traditional going all in and spending your entire life inside a workshop and till you make it huge, its full time work and no play.
Help me decide which one to pursue? I love the way to present myself as an industrialist , help the community of workers and their family , make a name for myself in the society, build something that speaks my legacy. However I am drawn to the meeting of new people, culture, differnet currencies, making new connections , trading , economics, numbers, researching - help me to chose my career.
